apiVersion: v1
data:
  KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: a2Fma2ExMjM=
  KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: a2Fma2ExMjM=
  KAFKA_CLUSTERS_2_PROPERTIES_SSL_KEYSTORE_PASSWORD: alN5MUBpYWdlMGt5bVN1QEVkRU4K
  KAFKA_CLUSTERS_2_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: alN5MUBpYWdlMGt5bVN1QEVkRU4K
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD":"a2Fma2ExMjM=","KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD":"a2Fma2ExMjM=","KAFKA_CLUSTERS_1_PROPERTIES_SSL_KEYSTORE_PASSWORD":"alN5MUBpYWdlMGt5bVN1QEVkRU4K","KAFKA_CLUSTERS_1_PROPERTIES_SSL_TRUSTSTORE_PASSWORD":"alN5MUBpYWdlMGt5bVN1QEVkRU4K"},"kind":"Secret","metadata":{"annotations":{},"name":"ssl-secret","namespace":"ansible"},"type":"Opaque"}
  creationTimestamp: "2024-11-01T07:31:14Z"
  name: ssl-secret
  namespace: ansible
  resourceVersion: "4495361"
  uid: 03d9f2ad-91ec-41a1-9c12-7716632c09fe
type: Opaque
